version: '2'
volumes:
    influxdbvol:

services:
    influxdb:
        image: influxdb:1.8
        restart: always
        container_name: influxdb
        ports:
            - "28086:8086"
            - "25826:25826/udp"
        volumes:
            - influxdbvol:/var/lib/influxdb
            - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
            - /usr/share/collectd/types.db:/usr/share/collectd/types.db:ro
        environment:
            - INFLUXDB_DB=collectd
            # Automatically initializes a database with the name of this environment variable.
#            - INFLUXDB_HTTP_AUTH_ENABLED=true
#            - INFLUXDB_ADMIN_USER=influxadmin
#            - INFLUXDB_ADMIN_PASSWORD=
#            - INFLUXDB_USER=ifxusr
#            - INFLUXDB_USER_PASSWORD=
#            - INFLUXDB_READ_USER=INFLUXDB_USER=iflxusrr
#            - INFLUXDB_READ_USER_PASSWORD=
#            - INFLUXDB_WRITE_USER=ifxusrw
#            - INFLUXDB_WRITE_USER_PASSWORD=
    chronograf:
        image: chronograf
        restart: always
        container_name: chronograf
        ports: 
            - "28888:8888"
    grafana:
        # may need a fixed version, otherwise it is current master branch
        image: grafana/grafana
        restart: always
        container_name: grafana
        ports:
            - "28080:3000"
    mosquitto:
        image: eclipse-mosquitto
        container_name: mosquitto
        restart: always
        ports:
            - "21883:1883"
            - "29001:9001"

